-- SALON WEBSITE DATABASE - PostgreSQL

-- Run this after connecting to your salon database.

CREATE TYPE public.account_type AS ENUM
    ('Customer', 'Employee', 'Admin');

CREATE TABLE public.users (
    users_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_role public.account_type NOT NULL DEFAULT 'Customer',
    user_email VARCHAR(255) NOT NULL UNIQUE,
    user_password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.category (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE public.services (
    services_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(150) NOT NULL,
    service_description TEXT,
    service_price NUMERIC(10,2) NOT NULL,
    deposit_amount NUMERIC(10,2) NOT NULL,
    duration_minutes INT NOT NULL,
    category_id INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT services_category_fk
        FOREIGN KEY (category_id)
        REFERENCES public.category(category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT service_price_check
        CHECK (service_price >= 0),

    CONSTRAINT deposit_amount_check
        CHECK (deposit_amount >= 0 AND deposit_amount <= service_price),

    CONSTRAINT duration_check
        CHECK (duration_minutes > 0)
);

CREATE TABLE public.appointments (
    appointments_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    service_id INT NOT NULL,
    appointment_datetime TIMESTAMP NOT NULL,
    service_price NUMERIC(10,2) NOT NULL,
    deposit_amount NUMERIC(10,2) NOT NULL,
    appointment_status VARCHAR(30) NOT NULL DEFAULT 'pending_payment',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT appointments_service_fk
        FOREIGN KEY (service_id)
        REFERENCES public.services(services_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT appointment_price_check
        CHECK (service_price >= 0),

    CONSTRAINT appointment_deposit_check
        CHECK (deposit_amount >= 0 AND deposit_amount <= service_price),

    CONSTRAINT appointment_status_check
        CHECK (appointment_status IN (
            'pending_payment',
            'confirmed',
            'completed',
            'cancelled',
            'no_show'
        ))
);

CREATE TABLE public.payments (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'GHS',
    payment_reference VARCHAR(255) NOT NULL UNIQUE,
    payment_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    payment_method VARCHAR(50),
    paid_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT payments_appointment_fk
        FOREIGN KEY (appointment_id)
        REFERENCES public.appointments(appointments_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT payment_amount_check
        CHECK (amount > 0),

    CONSTRAINT payment_status_check
        CHECK (payment_status IN (
            'pending',
            'successful',
            'failed',
            'refunded'
        ))
);

CREATE TABLE public.portfolio (
    portfolio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(2048) NOT NULL,
    portfolio_title VARCHAR(100) NOT NULL,
    portfolio_description TEXT,
    services_id INT NULL,

    CONSTRAINT portfolio_service_fk
        FOREIGN KEY (services_id)
        REFERENCES public.services(services_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE public.reviews (
    reviews_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NULL,
    review_rating SMALLINT NOT NULL,
    review_text TEXT,
    review_author VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_approved BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT reviews_user_fk
        FOREIGN KEY (user_id)
        REFERENCES public.users(users_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT review_rating_check
        CHECK (review_rating BETWEEN 1 AND 5)
);


CREATE TABLE public.messages (
    message_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    message_text TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_appointments_datetime
    ON public.appointments(appointment_datetime);

CREATE INDEX idx_appointments_status
    ON public.appointments(appointment_status);

CREATE INDEX idx_payments_appointment
    ON public.payments(appointment_id);

CREATE INDEX idx_payments_status
    ON public.payments(payment_status);

CREATE INDEX idx_portfolio_service
    ON public.portfolio(services_id);
